/*This class is generated by the XMLParser program.
Author: Petar Angelov (Petaaar). GitHub: https://github.com/Petaaar.
The project source code: https://github.com/Petaaar/XMLParser.
Thanks for using my parser!*/
namespace SASH.Custom
{
    #region Dependencies
    //this region contains all assembly references used in the class
    using SASH;
    using SASH.Custom;
    using SASH.Hidden;
    using System.Collections;

    #endregion Dependencies

    ///<summary>A class, generated automatically via XMLParser. WRITE YOUR SUMMARY HERE!</summary>
    class Child
 : TestingClass1
    {
        ///<summary>Constructor. Generates a new instance of the class.</summary>
        public Child()
        {
            System.Console.WriteLine("Hello from child!");
        }

    }

}
